### ISSUE TITLE
[BUG][CRITICAL] Transfer of created tokens above 4 digits fails

### ISSUE THREAD

**Issue by mobiledude** [CREDITSCOM/node#51]
**Describe the bug**
When transferring tokens on CS blockchain any amount from 4 digits or higher will fail despite paying credits transfer fee and having a sufficient token balance
Only transactions up to the amount of 999 are succesfull, higher will fail

This was done with created Dutch BBQ Token on mainnet which was created by the default token smartcontract. This all was done via the iOS app.

**To Reproduce**
Mainnet

1. Go to ios app
2. initiate token transfer with the amount of one thousend BBQ tokens or more
3.Transaction will fail
4.fee is deducted from balance
5.receiving party gets notification of zero tokens received (Transaction history, fee is zero
![receiving party](https://user-images.githubusercontent.com/52012485/61913050-35fa3780-af3c-11e9-8cae-904f982e8ae0.jpg)
)
6.Monitor shows failed token transactions

**Expected behavior**
transfer of tokens to receiving party

**Screenshots**
added above

**Additional context**
https://monitor.credits.com/CreditsNetwork/account/3ABKJowm9aqPKkYMLcxjHdtH5SkicQhV2zuf2nGK6qMi

**Comment by PresidentNavalny** [comment]
Hi. This bug is not critical. You need to show the bug in the testnet network and in the first stage the bugs related to the web wallet, mobile wallet, etc., do not participate in the bug bounty program. Full information related to the first stage of the bug bounty you can see here https://developers.credits.com/en/NewsPage/Credis_Bug_Bounty
![Безымянный](https://user-images.githubusercontent.com/51534826/61918183-2f2ded80-af59-11e9-873a-35de1923fed9.png)
![Безымянный2](https://user-images.githubusercontent.com/51534826/61918197-3654fb80-af59-11e9-8e41-e81931ef88ba.png)

**Comment by botstorm** [comment]
test

**Comment by mobiledude** [comment]
Hi, 

to be honest, I do not care if it is not part of bugbounty. I Just want to log an issue on mainnet. If you want you can remove BB labels, I do not know how to do that

**Comment by botstorm** [comment]
@mobiledude please describe the error
